_wandb:
    value:
        cli_version: 0.22.0
        e:
            v4vcaim82h75yla2kjeuzud1ryybfbxy:
                args:
                    - -n
                    - "4"
                    - --tiles
                    - "200"
                    - --alphabet
                    - "3"
                    - --mode
                    - hidden
                    - --canvas-m
                    - "40"
                    - --ants
                    - "8"
                    - --iters
                    - "20"
                codePath: benchmark.py
                codePathLocal: benchmark.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "117440507904"
                        used: "111990382592"
                email: shoraaa@protonmail.com
                executable: D:\Research\2dssp\.venv\Scripts\python.exe
                git:
                    commit: e482e0d5a5a59fdc666f95fe6e576d985caa1c69
                    remote: https://github.com/shoraaa/2dssp.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-4637b97d-ccc4-6b4c-507b-591b1d4b68c3
                host: Shora-Laptop
                memory:
                    total: "16867049472"
                os: Windows-10-10.0.26100-SP0
                program: D:\Research\2dssp\benchmark.py
                python: CPython 3.11.13
                root: D:\Research\2dssp
                startedAt: "2025-09-27T09:14:27.426274Z"
                writerId: v4vcaim82h75yla2kjeuzud1ryybfbxy
        m: []
        python_version: 3.11.13
        t:
            "3":
                - 2
                - 15
                - 16
            "4": 3.11.13
            "5": 0.22.0
            "8":
                - 3
            "12": 0.22.0
            "13": windows-amd64
Q:
    value: 16
alpha:
    value: 1
beta:
    value: 3
enable_compaction:
    value: false
epsilon:
    value: 1
gamma:
    value: 1
iterations:
    value: 20
lambda:
    value: 0.05
n_ants:
    value: 8
n_tiles:
    value: 200
n_workers:
    value: 8
random_seed:
    value: 123
rho:
    value: 0.1
tile_size:
    value: 4
